ci:
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/theendlessriver13/double-indent
    rev: 0.1.4
    hooks:
    -    id: double-indent
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: [numpy>=1.22.2]
# jupyter hooks
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
        # the hook below are called via an unsupported interface, this may break at some point
    -   id: nbqa
        name: debug-statements-jupyter
        args: [pre_commit_hooks.debug_statement_hook]
        additional_dependencies: [pre-commit-hooks]
    -   id: nbqa
        name: remove-trailing-whitespace-jupyter
        args: [pre_commit_hooks.trailing_whitespace_fixer]
        additional_dependencies: [pre-commit-hooks]
    -   id: nbqa
        name: flake8-jupyter
        args: [flake8]
        additional_dependencies: [flake8]
    -   id: nbqa
        name: autopep8-jupyter
        args: [autopep8, -i]
        additional_dependencies: [autopep8]
    -   id: nbqa
        name: double-quote-string-fixer-jupyter
        args: [pre_commit_hooks.string_fixer]
        additional_dependencies: [pre-commit-hooks]
    -   id: nbqa
        name: Reorder python import-jupyter
        args: [reorder_python_imports]
        additional_dependencies: [reorder-python-imports]
    -   id: nbqa
        name: double-indent
        args: [double_indent]
        additional_dependencies: [double-indent]
    -   id: nbqa
        name: add-trailing-comma
        args: [add_trailing_comma, --py36-plus]
        additional_dependencies: [add-trailing-comma]
    -   id: nbqa
        name: mypy-juypter
        args: [mypy, --ignore-missing-imports, --scripts-are-modules]
        additional_dependencies: [reorder-python-imports, mypy, numpy>=1.22.2]
